spring:
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8086

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka
